# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yertle_dash.ui'
#
# Created: Sat Jan 19 09:06:44 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 78)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.pbRTarget = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRTarget.sizePolicy().hasHeightForWidth())
        self.pbRTarget.setSizePolicy(sizePolicy)
        self.pbRTarget.setMinimumSize(QtCore.QSize(0, 10))
        self.pbRTarget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.pbRTarget.setFont(font)
        self.pbRTarget.setAutoFillBackground(False)
        self.pbRTarget.setMinimum(-200)
        self.pbRTarget.setMaximum(200)
        self.pbRTarget.setProperty("value", 0)
        self.pbRTarget.setObjectName("pbRTarget")
        self.gridLayout.addWidget(self.pbRTarget, 1, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.pbRVel = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRVel.sizePolicy().hasHeightForWidth())
        self.pbRVel.setSizePolicy(sizePolicy)
        self.pbRVel.setMinimumSize(QtCore.QSize(0, 10))
        self.pbRVel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.pbRVel.setFont(font)
        self.pbRVel.setMinimum(-200)
        self.pbRVel.setMaximum(200)
        self.pbRVel.setProperty("value", 0)
        self.pbRVel.setObjectName("pbRVel")
        self.gridLayout.addWidget(self.pbRVel, 3, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 4, 1, 1)
        self.pbLVel = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLVel.sizePolicy().hasHeightForWidth())
        self.pbLVel.setSizePolicy(sizePolicy)
        self.pbLVel.setMinimumSize(QtCore.QSize(0, 10))
        self.pbLVel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.pbLVel.setFont(font)
        self.pbLVel.setMinimum(-200)
        self.pbLVel.setMaximum(200)
        self.pbLVel.setProperty("value", 0)
        self.pbLVel.setObjectName("pbLVel")
        self.gridLayout.addWidget(self.pbLVel, 3, 1, 1, 1)
        self.pbLTarget = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLTarget.sizePolicy().hasHeightForWidth())
        self.pbLTarget.setSizePolicy(sizePolicy)
        self.pbLTarget.setMinimumSize(QtCore.QSize(0, 10))
        self.pbLTarget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.pbLTarget.setFont(font)
        self.pbLTarget.setAutoFillBackground(False)
        self.pbLTarget.setMinimum(-200)
        self.pbLTarget.setMaximum(200)
        self.pbLTarget.setProperty("value", 0)
        self.pbLTarget.setObjectName("pbLTarget")
        self.gridLayout.addWidget(self.pbLTarget, 1, 1, 1, 1)
        self.pb12V = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb12V.sizePolicy().hasHeightForWidth())
        self.pb12V.setSizePolicy(sizePolicy)
        self.pb12V.setMinimumSize(QtCore.QSize(0, 10))
        self.pb12V.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.pb12V.setFont(font)
        self.pb12V.setProperty("value", 24)
        self.pb12V.setObjectName("pb12V")
        self.gridLayout.addWidget(self.pb12V, 1, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 5, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.pbRMotor = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbRMotor.sizePolicy().hasHeightForWidth())
        self.pbRMotor.setSizePolicy(sizePolicy)
        self.pbRMotor.setMinimumSize(QtCore.QSize(0, 10))
        self.pbRMotor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.pbRMotor.setFont(font)
        self.pbRMotor.setMinimum(-255)
        self.pbRMotor.setMaximum(255)
        self.pbRMotor.setProperty("value", 0)
        self.pbRMotor.setObjectName("pbRMotor")
        self.gridLayout.addWidget(self.pbRMotor, 2, 3, 1, 1)
        self.pbLMotor = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLMotor.sizePolicy().hasHeightForWidth())
        self.pbLMotor.setSizePolicy(sizePolicy)
        self.pbLMotor.setMinimumSize(QtCore.QSize(0, 10))
        self.pbLMotor.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.pbLMotor.setFont(font)
        self.pbLMotor.setMinimum(-255)
        self.pbLMotor.setMaximum(255)
        self.pbLMotor.setProperty("value", 0)
        self.pbLMotor.setObjectName("pbLMotor")
        self.gridLayout.addWidget(self.pbLMotor, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.pbLapBat = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLapBat.sizePolicy().hasHeightForWidth())
        self.pbLapBat.setSizePolicy(sizePolicy)
        self.pbLapBat.setMinimumSize(QtCore.QSize(0, 10))
        self.pbLapBat.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.pbLapBat.setFont(font)
        self.pbLapBat.setProperty("value", 24)
        self.pbLapBat.setObjectName("pbLapBat")
        self.gridLayout.addWidget(self.pbLapBat, 2, 5, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.tbLWheel = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbLWheel.sizePolicy().hasHeightForWidth())
        self.tbLWheel.setSizePolicy(sizePolicy)
        self.tbLWheel.setMinimumSize(QtCore.QSize(0, 20))
        self.tbLWheel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.tbLWheel.setFont(font)
        self.tbLWheel.setObjectName("tbLWheel")
        self.gridLayout.addWidget(self.tbLWheel, 4, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 2, 1, 1)
        self.tbRWheel = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbRWheel.sizePolicy().hasHeightForWidth())
        self.tbRWheel.setSizePolicy(sizePolicy)
        self.tbRWheel.setMinimumSize(QtCore.QSize(0, 20))
        self.tbRWheel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.tbRWheel.setFont(font)
        self.tbRWheel.setObjectName("tbRWheel")
        self.gridLayout.addWidget(self.tbRWheel, 4, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 4, 1, 1)
        self.tbDebug = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbDebug.sizePolicy().hasHeightForWidth())
        self.tbDebug.setSizePolicy(sizePolicy)
        self.tbDebug.setMinimumSize(QtCore.QSize(0, 20))
        self.tbDebug.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.tbDebug.setFont(font)
        self.tbDebug.setObjectName("tbDebug")
        self.gridLayout.addWidget(self.tbDebug, 4, 5, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.pbWifi = QtGui.QProgressBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbWifi.sizePolicy().hasHeightForWidth())
        self.pbWifi.setSizePolicy(sizePolicy)
        self.pbWifi.setMinimumSize(QtCore.QSize(0, 10))
        self.pbWifi.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.pbWifi.setFont(font)
        self.pbWifi.setProperty("value", 24)
        self.pbWifi.setObjectName("pbWifi")
        self.gridLayout.addWidget(self.pbWifi, 3, 5, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Yertle Dashboard", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRTarget.setFormat(QtGui.QApplication.translate("MainWindow", "%v mm/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Vel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRVel.setFormat(QtGui.QApplication.translate("MainWindow", "%v mm/s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Lap Bat", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLVel.setFormat(QtGui.QApplication.translate("MainWindow", "%v mm/s", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLTarget.setFormat(QtGui.QApplication.translate("MainWindow", "%v/100 mm/s", None, QtGui.QApplication.UnicodeUTF8))
        self.pb12V.setFormat(QtGui.QApplication.translate("MainWindow", "%v", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Target", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "12V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Target", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.pbRMotor.setFormat(QtGui.QApplication.translate("MainWindow", "%v", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLMotor.setFormat(QtGui.QApplication.translate("MainWindow", "%v", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Vel", None, QtGui.QApplication.UnicodeUTF8))
        self.pbLapBat.setFormat(QtGui.QApplication.translate("MainWindow", "%p%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Wheel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Wheel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.pbWifi.setFormat(QtGui.QApplication.translate("MainWindow", "%p%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Wifi", None, QtGui.QApplication.UnicodeUTF8))

